[TOC]

# 异常与断言

## 1. 异常

假设在 Java 程序运行期间发生了异常，这个异常可大可小。对于小的异常，程序应该返回到一个安全的状态，并且提示用户，让用户执行其他的操作；对于大的异常，则应该为用户保存工作状态，并且终止程序的运行。

要做到上述这些并不容易，Java 提供了一套异常处理机制，能够将控制权从发生异常的代码转移到能够处理异常的代码中。这就需要**抛出**异常，让错误处理器来接收它，并处理。

**在 Java 中，使用异常类来表示一类异常及其原因。异常类都派生自 `Throwable` 类。`Throwable` 的直接子类有两个：`Error` 和 `Exception`：**

1. `Error`，Java 运行时系统内部错误和资源耗尽错误，**这类错误非常严重**，除了通知用户程序即将停止，你几乎无能为力。你的程序中不应该出现这类异常。

2. `Exception`，**这类异常又派生出两类，一类是 `RuntimeException`，表示运行时异常；另一类就是非运行时异常。**

   一般规则是：由编程错误导致的异常属于 `RuntimeException`；而如果程序没问题，但是由于像 I/O 出现了错误的这类问题导致的异常属于非运行时异常。

   常见的 `RuntimeException` 原因包括：

   1. 数组越界访问。
   2. 访问 `null` 指针。
   3. 错误的类型转换。
   4. 除法时除数为 0。
   5. ...

   如果出现了 `RuntimeException` 异常，那么一定是程序员自己的问题。

**所有派生自 `Error` 和 `RuntimeException` 的异常称为非检查型异常，其他异常称为检查型异常。**

非检查型异常一般由 JVM 处理，而非检查型异常则需要程序员处理，或者一直向上层抛出直到 JVM 接收到它。编译器将会检查程序员是否继续向上抛出检查型异常或设置了检查型异常处理器，如果没有，则不能通过编译。

### 1.1 声明检查型异常

所有检查型异常要么被捕获，要么继续向上抛出。如果一个方法可能抛出检查型异常，那么就要在方法上函数参数后 `(` 前添加 `throws` 说明。比如：

```java
public void readTxt() throws IOException {
    
}
```

这告诉开发者和编译器，该方法可能抛出 `IOException`，由于是可能，所以即使没有抛出，也能通过编译。

如果另一个开发者调用了这个方法，那么他会收到一个警告：此方法可能抛出 xxx 异常。这时候，开发者就需要处理这个异常或者继续向上抛出（为他自己的方法也添加 `throws` 说明）。

**如果方法可能抛出多个检查型异常，则需要全部声明，并且使用逗号隔开**。

非检查型异常也可以声明，不会报错，但是不提倡这么做。

如果子类重写的父类的方法中也声明了会抛出检查型异常，那么子类可以处理它，即根本不抛出异常；或者是抛出更具体的异常，即**子类可以抛出父类方法所声明的异常的子类异常**。但是，**子类不能抛出父类没有声明的异常**。

由于异常也有层级关系，因此可以使用一个总的 `IOException` 声明来说明可能抛出 I/O 异常，内部可能抛出原本的 `IOException`，也可能抛出 `FileNotFoundException` 等 `IOException` 的子类。

### 1.2 抛出异常

使用 `throw` 关键字可以抛出一个异常体系的类的实例，比如：

```java
public void readTxt() throws IOException {
    // ...
    
    throw new IOException();
    
    // ...
}
```

一旦抛出了异常而未捕获，那么该方法立即结束。

Java 内置了很多异常类，如果你能找到一个满足你需求的类，`new` 出来抛出即可。但是如果不能，我们也可以自定义异常类。

### 1.3 自定义异常类

自定义的异常类一般继承自 `Exception`，更具体一点，可以根据异常的大类继承自特定的非运行时异常，比如 `IOException`。

自定义的异常类一般包含两个构造器，一个是无参构造器，另一个构造器接受一个 `String` 参数，表示错误信息。这是符合规范的，Java 内置的异常类基本都符合这个规则。

比如：

```java
public class FileFormatException extends IOException {
    public FileFormatException() {

    }

    public FileFormatException(String msg) {
		super(msg);
    }
}
```

### 1.4 捕获异常

Java 使用 `try-catch-finally` 语法捕捉异常：

```java
try {
    // 可能会产生错误的代码
} catch (异常类型 异常类变量) {
    // 该异常类型的处理代码
} finally {
    // 无论是否发生异常都会执行的代码
}
```

其中 `catch` 子句的异常类型表明该子句能够捕捉到该异常类型及其子类类型的实例，使用异常类变量来接收捕捉到的异常类实例，通常用 `e` 表示。

可以省略 `catch` 或者 `finally`，但是必须要有其中之一跟在 `try` 后。

`catch` 可以有多个，因为一个 `catch` 只能捕捉到 `catch` 中声明的异常类型及其子类异常类型，如果多个 `catch` 都可以捕捉某个异常，那么只有最前面的 `catch` 能够成功捕捉到。

当多个 `catch` 捕捉的异常没有继承关系时，并且对它们的处理也相同时，可以在一个 `catch` 中使用 `|` 符号分隔多个异常类型来捕捉。比如：

```java
try {
    // ...
} catch (IOException | UnknownHostException e) {
    e.printStackTrace();
}
```

如果 `try` 中未发生任何异常，那么会跳过所有 `catch` 子句，来到 `finally`（如果有的话）。

如果 `try` 中发生的异常没有一个 `catch` 能捕捉，那么就立刻来到 `finally`（如果有的话），然后退出该方法。

在前面的学习中，我们知道检查型异常要声明或者捕捉，才能通过编译，如果声明了就要继续抛出，否则就要捕捉处理。那么，何时该抛出，何时该处理呢？

答案是：**捕捉你知道该如何处理的异常，继续抛出你不知道的异常。**

> **`finally`**
>
> `finally` 非常强大，无论有没有发送异常，都会执行 `finally` 中的语句，甚至于，你在 `try` 或 `catch` 中包含一个 `return`，在正式返回之前仍然会执行 `finally` 中的语句。
>
> 那么问题就来了，如果 `try` 和 `finally` 都有 `return` 语句，以谁的返回值为准呢？这个问题我们试验一下就知道了：
>
> ```java
> public class Main {
>     public static void main(String[] args) {
>         System.out.println(tryTest());
>         
>     }
>     
>     private static int tryTest() {
>         try {
>             return 1;
>         } finally {
>             return 0;
>         }
>     }
> }
> ```
>
> 答案是 `return 0`。

#### 1.4.1 异常类的常用方法及异常链

在 `catch` 中我们会使用异常变量 e 接收捕捉到的异常类型实例，它通常会有一些方法，如下表所示，其中，使用 `Exception` 代表任意异常类型：

| 构造方法                                     | 说明                                                 |
| -------------------------------------------- | ---------------------------------------------------- |
| `new Exception()`                            | 构造一个新的该类型异常                               |
| `new Exception(String msg)`                  | 构造一个带有指定详细消息的该类型异常                 |
| `new Exception(Throwable cause)`             | 构造一个具有指定原因的该类型异常                     |
| `new Exception(String msg, Throwable cause)` | 构造一个带有指定详细消息，且具有指定原因的该类型异常 |

一般来说，异常类都具有这些构造函数，实际中，要根据异常类型仔细选择。

| 异常方法                               | 说明                                                         |
| -------------------------------------- | ------------------------------------------------------------ |
| `Throwable initCause(Throwable cause)` | 将此 `Throwable` 的原因初始化为指定值。                      |
| `String toString()`                    | 返回此 `Throwable` 的简短描述。结果是以下内容的串联：<br/>* 这个对象的类名<br/>* 冒号和空格<br/>* 调用此对象的 `getLocalizedMessage` 方法的结果 |
| `void printStackTrace()`               | 将此 `Throwable` 及其回溯打印到标准错误流。                  |
| `void printStackTrace(PrintStream s)`  | 将此 `Throwable` 及其回溯打印到指定 `PrintStream` 流。       |
| `void printStackTrace(PrintWriter s)`  | 将此 `Throwable` 及其回溯打印到指定 `PrintWriter` 流。       |
| `String getMessage()`                  | 返回此 `Throwable` 的详细消息字符串。                        |
| `String getLocalizedMessage()`         | 创建此 `Throwable` 的本地化描述。                            |
| `Throwable getCause()`                 | 获取导致此异常的原因异常。                                   |

这里涉及到异常链，因为异常很可能是由封装的方法引起的，程序员需要知道具体发生在何处。这种情况下，把捕获到的异常包装进一个新的异常中，继续抛出新的异常，就完成了异常的封装。

可以根据上面列出的方法，获取异常的信息，根源等，方便快速找到异常。

#### 1.4.2 分析异常堆栈轨迹

堆栈轨迹是程序执行过程中某个特定点上所有挂起的方法调用的一个列表。

我们最常见的报错：

![image-20220129122838773](https://fastly.jsdelivr.net/gh/Faraway002/typora/images/image-20220129122838773.png)

就是一个堆栈轨迹，异常堆栈轨迹详细的展示了错误发生在哪一行。

通过堆栈轨迹和异常链，我们可以很快定位错误，比如 SpringBoot 应用程序中可能出现的异常，这个堆栈轨迹相当长：

![image-20220129123255532](https://fastly.jsdelivr.net/gh/Faraway002/typora/images/image-20220129123255532.png)

最终，我们定位到发生在我们自己编写的 `DemoApplication.java` 的第 15 行。

### 1.5 try-with-resources 语法

我们通常会使用 `finally` 语句关闭一些资源，比如 I/O 流，JDBC 的 `Statement` 等，这样就形成了一种代码定式：

```java
try {
    // 打开某种资源
} catch () {
    // 处理资源时发生异常后，捕获
} finally {
    // 关闭资源
}
```

这些资源是十分宝贵的，用完了需要及时关闭；处理资源时，出错的可能性也很大，很多涉及资源处理方法会声明要抛出检查型异常。

关闭这些资源虽然是必要的，但是却十分繁琐。这是因为资源在关闭时可能还会出现异常，导致这种情况：

```java
try {
    // 打开某种资源
} catch () {
    // 处理资源时发生异常后，捕获
} finally {
    try {
    	// 关闭资源
    } catch () {
        
    }
}
```

这时可以使用 try-with-resources 语法，把资源定义在 try 后：

```java
try (ResourceType var = xxx; ResourceType2 var2 = xxx; ...) {
    // 处理资源
} catch () {
    
} finally {
    // 除了关闭资源外的其他代码
}
```

这样一来，不需要写 `finally` 子句，就可以自动关闭资源。关闭资源如果发生了异常，就会抛出 `try` 中可能抛出的异常，然后把关闭资源的异常附加到这个抛出的异常中一起抛出。

这可以通过异常类的 `addSuppressed` 实现，它把一个异常抑制，然后把这个异常附加到调用者身上。可以通过 `getSuppressed` 获取被抑制的异常。

> **try-with-resources 的原理**
>
> 一般的资源类都会实现 `AutoClosable` 接口，表示可以自动关闭，内部仅有一个 `close` 方法。
>
> try-with-resources 中会自动调用 try 声明中的资源的 `close` 方法，只要它们实现了 `AutoClosable` 接口。
>
> `Closable` 是原来的老接口，在 Java 7 之后改为继承自 `AutoClosable` 接口，所以带有 `Closable` 的接口也可以被自动关闭。

## 2. 断言

程序逻辑需要某个条件一定满足，而程序员为了确定某个条件一定满足，可以测试这个条件，**如果测试失败就立即停止程序，测试成功则当作什么都没发生**。这样的测试叫做断言。

断言的形式为：`assert 布尔条件 : message;`。断言的原理是如果布尔条件结果为 `false`，则立即抛出一个 `AssertionError`，并且把 `message` 作为消息传递给这个 `Error`。

注意，断言抛出的是 `Error`，属于非常严重的错误。

断言和普通条件最大的区别是，断言可以被禁用，在代码中可以一直保留着。如果被禁用，虽然代码中存在断言代码，但是却不会运行。这带来的好处就是，**在程序的测试阶段可以一直启用断言，而到了程序的发布阶段，可以禁用断言，不因为存在过多的判断而影响性能。**

默认情况下，断言是禁用的，使用 `java` 命令的 `-ea` 选项启用，使用 `-da` 禁用。

> **类加载器与断言**
>
> 类一般是由类加载器加载到虚拟机中的，断言也是类加载器的行为，因此 `-ea` 和 `-da` 只适用于被类加载器加载的类。
>
> 而 JVM 启动时就会加载的类称为系统类，使用 `-esa` 选项可以启用系统类的断言。

看一个小例子：

```java
static void sort(int[] a); // 这个方法对数组排序，但是数组不能为空

// 方法中
assert a != null;
sort(a);
```
